name: Build Kernel - The Final One

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev bc clang llvm curl git unzip
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Checkout Kernel Source
        uses: actions/checkout@v4
        with:
          repository: realme-kernel-opensource/realme_GT7pro-AndroidV-kernel-source
          path: kernel
          fetch-depth: 0
      - name: Set Build Environment
        run: |
          echo "ARCH=arm64" >> $GITHUB_ENV
          echo "KBUILD_BUILD_USER=GitHubActions" >> $GITHUB_ENV
          echo "KBUILD_BUILD_HOST=GitHub" >> $GITHUB_ENV
          echo "CC=clang" >> $GITHUB_ENV
          echo "CLANG_TRIPLE=aarch64-linux-gnu-" >> $GITHUB_ENV

      # 7. カーネルのビルド
      - name: Build Kernel
        run: |
          cd kernel
          pwd # 現在のディレクトリを確認
          ls -l Init/Kconfig # Init/Kconfig が存在することを確認
          ls -l oplus_cpu/Kconfig # oplus_cpu/Kconfig が存在することを確認
          ls -l kernel/oplus_cpu/Kconfig # Kconfigが探しているパスを確認 (もし 'kernel/' ディレクトリの下にいる場合)
          make O=out oplus_debug_defconfig
          make O=out defconfig
          echo "CONFIG_KSU=y" >> out/.config
          echo "CONFIG_SUSFS=y" >> out/.config
          make O=out -j$(nproc --all)
          path: out/arch/arm64/boot/Image
          
          # KernelSUとsusfsを有効化
          echo "CONFIG_KSU=y" >> kernel/out/.config
          echo "CONFIG_SUSFS=y" >> kernel/out/.config
          
          # ビルドを実行
          make O=out -j$(nproc --all)

      # 8. 完成したカーネルイメージをアップロード
      - name: Upload Kernel Image
        uses: actions/upload-artifact@v4
        with:
          name: kernel-image
          path: kernel/out/arch/arm64/boot/Image
