name: Build Kernel - The Final One

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      # 1. 必要なパッケージをインストール
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev bc clang llvm curl git

      # 6. ビルド用の環境変数を設定
      - name: Set Build Environment
        run: |
          echo "ARCH=arm64" >> $GITHUB_ENV
          echo "KBUILD_BUILD_USER=GitHubActions" >> $GITHUB_ENV
          echo "KBUILD_BUILD_HOST=GitHub" >> $GITHUB_ENV
          echo "CC=clang" >> $GITHUB_ENV
          echo "CLANG_TRIPLE=aarch64-linux-gnu-" >> $GITHUB_ENV

      # 7. カーネルのビルド
      - name: Build Kernel
        run: |
          make -C kernel O=out oplus_debug_defconfig
          
          # ビルド設定を生成
          make O=out defconfig
          
          # KernelSUとsusfsを有効化
          echo "CONFIG_KSU=y" >> kernel/out/.config
          echo "CONFIG_SUSFS=y" >> kernel/out/.config
          
          # ビルドを実行
          make O=out -j$(nproc --all)

      # 8. 完成したカーネルイメージをアップロード
      - name: Upload Kernel Image
        uses: actions/upload-artifact@v4
        with:
          name: kernel-image
          path: kernel/out/arch/arm64/boot/Image
