name: Build Kernel - The Final One

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      # 1. 必要なパッケージをインストール
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev bc clang llvm curl git

      # 2. カーネル本体のソースコードを `kernel` フォルダにチェックアウト (★★最終修正★★)
      - name: Checkout Kernel Source
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          path: kernel  # この一行が抜けていたことが全ての原因でした

      # 3. vendor（メーカー独自）のソースコードを `vendor_source` フォルダにチェックアウト
      - name: Checkout Vendor Source
        uses: actions/checkout@v4
        with:
          repository: realme-kernel-opensource/realme_GT7pro-AndroidV-vendor-source
          path: vendor_source
          fetch-depth: 1

      # 4. 不足しているフォルダを物理的に移動
      - name: Move Vendor Sources
        run: mv vendor_source/vendor/oplus/kernel/cpu kernel/oplus_cpu

      # 5. Kconfigの間違ったパスを2段階で修正
      - name: Patch Kconfig Paths
        run: |
          sed -i 's|source "kernel/oplus_cpu/Kconfig"|source "oplus_cpu/Kconfig"|' kernel/init/Kconfig
          sed -i 's|source "kernel/oplus_cpu/cpufreq_health/Kconfig"|source "cpufreq_health/Kconfig"|' kernel/oplus_cpu/Kconfig

      # 6. ビルド用の環境変数を設定
      - name: Set Build Environment
        run: |
          echo "ARCH=arm64" >> $GITHUB_ENV
          echo "KBUILD_BUILD_USER=GitHubActions" >> $GITHUB_ENV
          echo "KBUILD_BUILD_HOST=GitHub" >> $GITHUB_ENV
          echo "CC=clang" >> $GITHUB_ENV
          echo "CLANG_TRIPLE=aarch64-linux-gnu-" >> $GITHUB_ENV

      # 7. カーネルのビルド
      - name: Build Kernel
        run: |
          # URLからdefconfigを直接ダウンロード
          curl -L -o kernel/arch/arm64/configs/defconfig "https://raw.githubusercontent.com/miris74/realme_GT7pro-AndroidV-kernel-source/master/arch/arm64/configs/oplus_debug_defconfig"
          
          # ビルド設定を生成
          make -C kernel O=out defconfig
          
          # KernelSUとsusfsを有効化
          echo "CONFIG_KSU=y" >> kernel/out/.config
          echo "CONFIG_SUSFS=y" >> kernel/out/.config
          
          # ビルドを実行
          make -C kernel O=out -j$(nproc --all)

      # 8. 完成したカーネルイメージをアップロード
      - name: Upload Kernel Image
        uses: actions/upload-artifact@v4
        with:
          name: kernel-image
          path: kernel/out/arch/arm64/boot/Image
